remote_theme: zendesk/jekyll-theme-zendesk-garden@main

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


title:            Local Data Hub Documentation
permalink: pretty

search_enabled: true
auto_page_title: true

mermaid_enabled: true
mermaid_theme: forest

sidebar:
  - label: User Guide
    children:
    - label: User
      children:
        - Registrierung in SEEK
        - Profil bearbeiten
    - label: LDH
      children:
        - Projekt beitreten
        - Projekt erstellen
        - label: ISA Struktur erstellen
          children:
           - Investigation erstellen
           - Studie erstellen
           - Erstellen eines Assays
           - Erstellen einer Modellierungsanalyse
        - ISA Übersicht
        - Publikation hinzufügen
        - Investigation, Studie oder assay zitierfähig machen
        - Spezielle Benutzerrollen
        - Projekt Dashboard
      - label: ISA Nutzung für NFDI4Health
        children:
          - ISA Best Practice
  - label: Admin Guide
    children:
      - label: Einrichten
        children:
          - LDH Einrichtung mittels Docker Skript
          - LDH als Entwicklungssystem
          - LDH in einer Produktivumgebung
          - Verwendung in Docker
          - Solr einrichten
      - label: Verwalten
        children:
          - Admin panel
          

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
